### ISSUE TITLE
Panic while compiling add.code

### ISSUE THREAD

**Issue by lovesh** [JacobEberhardt/ZoKrates#47]
When compiling `https://github.com/JacobEberhardt/ZoKrates/blob/develop/examples/add.code` using `./zokrates compile -i ... `,i get a panic
```
thread 'main' panicked at 'Semantic analysis failed with: a is undefined', src/main.rs:222:29
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: zokrates::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:479
  10: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  11: std::rt::lang_start_internal
             at libstd/panicking.rs:458
             at libstd/panic.rs:358
             at libstd/rt.rs:58
  12: main
  13: __libc_st
```
The reason is that `main` method of `add.code` is missing argument. The code looks like this
```
def main():        // missing argument "a"
  b = a + 5
  c = a + b + a + 4
  d = a + c + a + b
  return b + c + d
```
It needs to look like this 
```
def main(a):      // or def main(private a):
  b = a + 5
  c = a + b + a + 4
  d = a + c + a + b
  return b + c + d
```
Changing to above code makes that panic disappear and compilation, setup, etc work

**Comment by Schaeff** [comment]
Thanks @lovesh, we did miss fixing the test pipeline and the examples when we added the semantic analyzer :)
